[general]
	#Allow harvesting with empty hand. If disabled, requires hoe.
	allowEmptyHand = true
	#Harvesting crops costs durability.
	damageTool = true
	#Automatically register crops.
	autoConfigMods = true
	#Chance of XP dropping on harvest.
	#Range: 0 ~ 100
	xpFromHarvestChance = 7
	#Amount of XP dropped on harvest.
	#Range: 0 ~ 10
	xpFromHarvestAmount = 4
	#Use range for XP drop, instead of set amount.
	xpFromHarvestUseRange = false
	#Range of XP dropped on harvest. Format: "min-max", example: "0-3"
	xpFromHarvestRangeAmount = "0-1"
	#Harvestable crops.
	#Format: "harvestState[,afterHarvest]", i.e. "minecraft:wheat[age=7]"
	#or "minecraft:cocoa[age=2,facing=north],minecraft:cocoa[age=0,facing=north]"
	#WARNING: If autoConfigMods is set to false, only crops defined here will work.
	#If not, it will just add to the auto-configured list.
	harvestableCrops = []
	#Blocks that right clicking should simulate click instead of breaking.
	#For blocks like berry bushes that have built-in right click harvest.
	harvestableBlocks = ["minecraft:sweet_berry_bush", "minecraft:cave_vines"]
	#Expand hoe range based on tier.
	expandHoeRange = true
	#Regular hoe (gold, wood, iron) expansion range.
	#Range: 1 ~ 5
	smallTierExpansionRange = 2
	#Regular hoe (gold, wood, iron) expansion range.
	#Range: 1 ~ 5
	highTierExpansionRange = 3
	#Expand hoe range by 1 for each level of efficiency enchantment level.
	expandHoeRangeEnchanted = false
	#Maximum range hoe can expand for harvesting.
	#This is the maximum of tier + efficiency enchantment.
	#Range: 1 ~ 11
	maxHoeExpansionRange = 11
	#List of individual hoe tools and their harvest tier. This is for modded items not covered.
	#Format: minecraft:wooden_hoe-0 (with number being tier)
	hoeItems = ["minecraft:wooden_hoe-0", "minecraft:stone_hoe-0", "eternal_starlight:glacite_hoe-4", "eternal_starlight:starlit_hoe-4", "eternal_starlight:starfire_hoe-4", "eternal_starlight:unrealium_hoe-4", "eternal_starlight:malarite_hoe-4", "eternal_starlight:pearlescent_hoe-4", "aether:skyroot_hoe-0", "aether:holystone_hoe-0", "aether:zanite_hoe-3", "aether:gravitite_hoe-4", "aether:valkyrie_hoe-4", "deep_aether:stratus_hoe-4"]
	#List of crops to blacklist from right-click harvest. Format: "modid:block"
	blacklistCrops = ["minecraft:torchflower_crop"]
	#List of mods to blacklist from right-click harvest. Format: "modid"
	blacklistMods = []
	#Allow machines, like Create's deployer, to harvest crops.
	allowFakePlayer = true
	#List of held items to blacklist from right-click harvest. Format: "modid:item"
	blacklistHeldItems = []
	#Automatically replant crops after harvesting.
	replantCrops = false
