showModName = false
scrollAround = false
keepCentered = false
expandedRecipeBook = false
hideReiJeiOverlay = true
settingsButton = true
enableBook = true
showAllRecipesInSurvival = true
partialCraftingEnabled = false
partialMarkingEnabled = true

[rbip]
enableRecipeBookIsPain = true
enableTabPage = true

[instantCraft]
showButton = true
enabled = false

[newRecipes]
unlockAll = false
enableBounce = false

[alternativeRecipes]
onHover = true
noGrouped = false
