enabled = false
enableFluidDiscovery = true
enableEffectDiscovery = true
filterIndex = true
displayCraftableInIndex = true
requireWorkstationForCraftable = true
displayWithUnknownWorkstation = true
exemptInventoryCrafting = true
requireCatalystsKnown = true
allowRecipeLookupForUndiscovered = true
allowUsageLookupForUndiscovered = false
blackoutUnknownInRecipes = true
obscureTooltips = false
showQuestionMarkOverlay = true
enableAdvancementDiscovery = true
