version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
bountiful = true
darkerdepths = true
eternal_starlight = true
nears = true
quark = true
ribbits = true
runes = true
piglinproliferation = true
easymagic = true
carved_wood = true
camping = true
luminous_butterflies = true
golemoverhaul = true
friendsandfoes = true
sporelight = true
aether_enhanced_extinguishing = true
selling_bin = true
ghosts = true
farmingforblockheads = true
village_taverns = true
plushie_buddies = true
aether = true
ore_creeper = true
additionaladditions = true
trmt = true
amendments = true
aether_treasure_reforging = true
snowrealmagic = true
block_factorys_bosses = true
moonlight = true
the_moth = true
terrarianmight = true
treechop = true
spell_engine = true
knightlib = true
mushroomquest = true
enderscape = true
nightlights = true
tinymultiblocklib = true
companions = true
paladins = true
deep_aether = true
items_displayed = true
cropcritters = true
snuffles = true
mythsandlegends = true
rottencreatures = true
hexerei = true
rogues = true
minecraft = true
nethers_exoticism = true
gipples_galore = true
unusualend = true
starcatcher = true
just_blahaj = true
betterarcheology = true
cozyhome = true
jewelry = true
waystones = true
bosses_of_mass_destruction = true
creeperoverhaul = true
archers = true
rosebackport = true
crittersandcompanions = true
enchantinginfuser = true
serene_shrubbery = true
