["Suspicious Bag"]
	#Items to be blacklisted from the Suspicious Bag
	"Item Blacklist (Suspicious Bag)" = ["oddaccessories:guts", "oddaccessories:homunculus", "oddaccessories:crown_of_nails", "oddaccessories:regret_of_a_salaryman", "oddaccessories:universal_attractor", "oddaccessories:heart_prop", "oddaccessories:unconditional_love", "oddaccessories:villager_mask", "oddaccessories:enlightening_tablet", "oddaccessories:malicious_tablet", "oddaccessories:clean_tablet", "oddaccessories:malicious_ring", "oddaccessories:enlightening_ring", "oddaccessories:mimic_ring"]
	#The denominator in the chance for a Suspicious Bag to drop from any mob. Example: 100 would make the chance 1/100. If you set it to 150, then the chance is 1/150
	"Suspicious Bag Drop Rate" = 125.0
	#The cooldown for a player to be able to find another bag in ticks (this applies after the player finds a bag)
	"Suspicious Bag Cooldown" = 3000.0

[Effects]
	#INFORMATION ON ALL EFFECTS: | The (Freedom) effect grants 10% more max health, attack speed, damage, armor toughness, and movement speed. | The (Happy) effect applies 20% more max health, movement speed, and attack speed. | The (Sad) effect applies greater gravity. | The (Tetanus) effect causes a certain percent of current HP to be removed on entity damage.
	"Explaining Effects" = "N/A"
	#This controls the % of current HP that is removed when you take damage while having Tetanus. The formula is current HP * tetanuspercent. Example: current HP * 0.70 is a 30% reduction of current HP
	"Tetanus Percent Damage" = 0.75

[General]
	#How much damage the homunculus deals when it cures negative potion effects. 1 = Half a heart.
	"Homunculus Damage" = 2.0
	#The negative effects the homunculus clears. NOTE: This is intended to clear all negative effects, including custom ones. If you have a modpack that has custom negative effects, feel free to include them in this list.
	"Homunculus Negative Effects" = ["minecraft:wither", "minecraft:poison", "minecraft:slowness", "minecraft:weakness", "minecraft:darkness", "minecraft:hunger", "minecraft:mining_fatigue", "minecraft:blindness", "minecraft:nausea", "oddaccessories:tetanus", "oddaccessories:sad"]
	#How many ticks of Tetanus the Crown of Nails applies 
	"Crown Of Nails Tetanus Length" = 120.0
	#How much XP is granted with the Broken Telephone
	"Broken Telephone XP" = 5.0
	#How much XP is granted with the Regret Of A Salaryman
	"Regret Of A Salaryman XP" = 75.0
	#The block range at which baby zombies can be attracted with the Collectible Meal Toy
	"Collectible Meal Toy Range" = 25.0
	#The block range at which villagers can be attracted with the Emerald Nose
	"Emerald Nose Range" = 16.0
	#The block range at which mobs can be attracted with the Universal Attractor
	"Universal Attractor Range" = 16.0
	#The block range in which the Old Sock applies slowness and nausea
	"Sock Range" = 6.0
	#The block range in which the Improvised Cross burns undead
	"Improvised Cross Range" = 10.0
	#The percent boost in healing provided by this item. Example: 10 is a 10% increased healing factor
	"Heartfelt Confession Healing Boost Percent" = 10.0
	#The percent boost in healing provided by this item. Example: 20 is a 20% increased healing factor
	"Unconditional Love Healing Boost Percent" = 20.0
	#The percent boost in damage provided by this item. Example: 10 is a 10% increased damage factor
	"Flaying Tool Percent Damage Boost" = 10.0
	#The percent boost in damage provided by this item. Example: 30 is a 30% increased damage factor
	"Malice Percent Damage Boost" = 30.0
	#The denominator in the chance for a reward upon waking. Example: 3 would make the reward chance upon waking 1/3. If you set it to 4, then the reward chance upon waking is 1/4
	"Sifting Jar Reward Chance" = 3.0
	#The percent of XP given (calculated from the XP remaining needed to gain a level). In this case, 0.01 would count towards 1 percent of the remaining XP needed to gain a level
	"Enlightening Tablet Percent" = 0.01
	#The percent boost in damage per kill provided by the Malicious Tablet. Example: 0.1 is a 0.1% increase in damage per kill you have
	"Malicious Tablet Percent Damage Boost" = 0.05
	#The cap in damage boost provided by the Malicious Tablet
	"Malicious Tablet Percent Damage Boost Cap" = 100.0
	#Whether or not the damage inversion still applies if the damage would deal more than 100% of the holder's health
	"Mirror Damage Scaling Cap" = false
	#The percent reduction in damage per death provided by Guts. Example: 0.1 is a 0.1% reduction in damage per death you have
	"Guts Percent Damage Reduction" = 0.1
	#The cap in damage reduction provided by Guts
	"Guts Percent Damage Reduction Cap" = 40.0
	#The max amount of nearby mobs the holder of the fiberglass cloak can be around
	"Fiberglass Cloak Max Mobs" = 3.0
	#The denominator in the chance for damage negation. Example: 3 would make the negation chance 1/3. If you set it to 4, then the negation chance is 1/4
	"Armored Knight Doll" = 5.0
	#The denominator in the portion of food the Clay Vessel stores. Example: 3 would make the Clay Vessel store 1/3 of consumed food. If you set it to 4, then it would be 1/4 of consumed food
	"Clay Vessel Portion" = 3.0
	#The percent boost in damage provided by this item. Example: 10 is a 10% increased damage factor
	"Malicious Ring Percent Damage Boost" = 20.0
	#The percent boost in damage reduced by this item. Example: 10 is a 10% damage reduction
	"Harmony Percent Damage Reduction" = 10.0
	#The number of blocks the holder falls before the Emergency Parachute deploys.
	"Emergency Parachute Fall Distance" = 12.0
	#The level of potion speed granted when the holder uses the Discipline Rod
	"Discipline Rod Speed Level" = 3.0
	#After Mimic death, how long the holder has to wait before being able to summon the Mimic again
	"Mimic Cooldown" = 15.0
	#How many hits it takes for the wheel to fully adapt to a type of damage
	"Wheel Adaption Hits" = 4.0
	#Whether or not the holder can harm their own mimic
	"Holder Harm Mimic" = false
